'use client';

import React, { useState } from 'react';
import { useSelector } from 'react-redux';
import { RootState } from '@/redux/store';
import { MainLayout } from '@/components/templates/MainLayout';
import { Card } from '@/components/atoms/Card';
import { Button } from '@/components/atoms/Button';
import { Sparkles, Bot, Save, Copy, CheckCircle2 } from 'lucide-react';
import { generateMoodPrompt } from '@/utils/aiSuggestion';

export default function AIPromptPage() {
  const { currentMood } = useSelector((state: RootState) => state.mood);
  const { tasks } = useSelector((state: RootState) => state.tasks);
  
  const [copied, setCopied] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  // Generate the raw prompt using the logic requested
  const systemPrompt = generateMoodPrompt(currentMood || 'neutral', tasks);

  const handleCopy = () => {
    navigator.clipboard.writeText(systemPrompt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveToDB = () => {
    // Scaffold for user's future Supabase API endpoint
    setIsSaving(true);
    setTimeout(() => {
      setIsSaving(false);
      alert("Ready to connect to Supabase API!");
    }, 1000);
  };

  return (
    <MainLayout>
      <div className="mb-8">
         <h1 className="text-4xl font-heading font-black bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent mb-3 flex items-center gap-3">
           <Sparkles className="text-primary" />
           AI Prompt Engine
         </h1>
         <p className="text-gray-500 font-medium text-lg">
           View and manage the raw system prompts generated by your mood and task data. Perfect for hooking into your future Supabase backend.
         </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Main Prompt Viewer */}
        <div className="lg:col-span-2 flex flex-col gap-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
          <Card className="p-0 overflow-hidden border border-primary/20 bg-white/50 dark:bg-slate-900/50 backdrop-blur-xl">
            <div className="bg-primary/5 dark:bg-primary/10 border-b border-primary/10 px-6 py-4 flex items-center justify-between">
              <div className="flex items-center gap-2 text-primary font-semibold">
                <Bot size={20} />
                <span>Generated System Prompt</span>
              </div>
              <button 
                onClick={handleCopy}
                className="text-gray-400 hover:text-primary transition-colors flex items-center gap-2 text-sm font-medium"
              >
                {copied ? <CheckCircle2 size={16} className="text-green-500" /> : <Copy size={16} />}
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
            <div className="p-6">
              <pre className="whitespace-pre-wrap font-mono text-sm text-gray-700 dark:text-gray-300 leading-relaxed bg-black/5 dark:bg-black/20 p-6 rounded-xl border border-gray-100 dark:border-gray-800">
                {systemPrompt}
              </pre>
            </div>
          </Card>
        </div>

        {/* Sidebar Controls */}
        <div className="flex flex-col gap-4 animate-in fade-in slide-in-from-bottom-4 duration-700">
          <Card className="p-6 glass-card border-none shadow-xl shadow-accent/5">
            <h3 className="font-heading font-bold text-lg mb-4 text-text">Context Parameters</h3>
            
            <div className="space-y-4 mb-6">
              <div>
                <p className="text-sm text-gray-500 mb-1">Active Mood</p>
                <div className="inline-block px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-bold capitalize">
                  {currentMood || 'None selected'}
                </div>
              </div>
              <div>
                <p className="text-sm text-gray-500 mb-1">Total Tasks Tracked</p>
                <div className="inline-block px-3 py-1 rounded-full bg-secondary/10 text-secondary text-sm font-bold">
                  {tasks.length} items
                </div>
              </div>
            </div>

            <Button 
              onClick={handleSaveToDB} 
              disabled={isSaving}
              className="w-full flex items-center justify-center gap-2 shadow-lg shadow-primary/20"
            >
              <Save size={18} />
              {isSaving ? 'Saving...' : 'Save to Supabase DB'}
            </Button>
            <p className="text-xs text-gray-500 mt-4 text-center">
              * Connect this button to your `supabaseClient` endpoint.
            </p>
          </Card>
        </div>

      </div>
    </MainLayout>
  );
}
